name: flutter_lan_sync_example
description: Demonstrates how to integrate the flutter_lan_sync package.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lan_sync:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
